import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

import NavbarShad from "@/components/navbar/NavbarShad";
import FullNavbar from "@/components/navbar/FullNavbar";
import { ThemeProvider } from "@/components/ThemeProvider";



const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {




  

  

  return (
    <html lang="en">
      <body className={inter.className}>
      <ThemeProvider
            attribute="class"
            defaultTheme="light"
            enableSystem
            disableTransitionOnChange
          >
            

     <FullNavbar/>
        {children}
        <div id="overlays"></div>
  
        </ThemeProvider>
      </body>
    </html>
  );
}
